version: '3.4'
services:
  mysql:
    container_name: mysql-prisma
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: prisma-test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - prisma_network
  prisma-project:
    container_name: prisma-project
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    command: yarn run start:migrate:dev
    depends_on:
      - mysql
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - prisma_network

networks:
  prisma_network:
    name: prisma_network
